### PR TITLE
Input control  kwashie

### PR DESCRIPTION
**Pull request by Kwash67**
Added nes module

### CODE REVIEW

**Comment by Enjimneering** [comment]
LGTM 👍

**Review by Enjimneering — COMMENTED** [review]
Module looks good, I won't merge into main yet because the info.yaml and test makefile need to be changed to reflect the addition of a new source file or the module will not be synthesized.

**Comment by Kwash67** [comment]
> Module looks good, I won't merge into main yet because the info.yaml and test makefile need to be changed to reflect the addition of a new source file or the module will not be synthesized.

Right, I'll do that and push as soon as possible. Thanks for pointing it out

**Comment by Enjimneering** [comment]
I updated the timings to work with a 50MHz clk.

**Review by Enjimneering — APPROVED** [review]
Input buffer needs to be added but base state is sufficient to be merged🫡

**Review by AnubhavAvinash — APPROVED** [review]

**Pull request merged**
